
[patch.crates-io]
ankurah = { path = "../ankurah/ankurah" }
ankql = { path = "../ankurah/ankql" }
ankurah-signals = { path = "../ankurah/signals" }
ankurah-websocket-server = { path = "../ankurah/connectors/websocket-server" }
ankurah-websocket-client-wasm = { path = "../ankurah/connectors/websocket-client-wasm" }
ankurah-storage-indexeddb-wasm = { path = "../ankurah/storage/indexeddb-wasm" }
ankurah-storage-sled = { path = "../ankurah/storage/sled" }
ankurah-storage-postgres = { path = "../ankurah/storage/postgres" }
